arena:
    min_area: 1000
    block_size: 9
    param1: 13
    kernel_factor: 5
    rangelow: 0
    rangeup: 255
    targets: 10
    columns: 1
    width: 80
    height: 15

fly:
    min_length: 0
    min_dist_arena: 2
    max_area: 200
    min_area: 0
    min_intensity: 80

tracker:   
    fps: 2
    experimenter: "Sayed"
    crop: 1
    N: 10
    fail: 'failed_arenas/'

arduino:
    board: Dummy

saver:
    path: "lemdt_results/LeMDTe27SL5a9e19f94de287e28f789825/LEARNER_001"
    video_format: "avi"
    fps: 2

blocks:
    folder: LeMDT/blocks/
    pattern: '.csv'

interface:
    duration: 200
    machine_id: "LeMDTe27SL5a9e19f94de287e28f789825"
