arena:
    min_area: 1000
    block_size: 9
    param1: 13
    kernel_factor: 5
    rangelow: 0
    rangeup: 255

fly:
    min_length: 0
    min_dist_arena: 2
    max_area: 200
    min_area: 0
    min_intensity: 80

tracker:   
    fps: 2
    experimenter: "Sayed"
    crop: 1
    store: "data/store"
    N: 10
    fail: 'failed_arenas/'

arduino:
    store: "metadata/store"
    board: ArduinoMega

blocks:
    folder: LMDT/blocks/
    pattern: '.csv'

interface:
    duration: 200
