arena:
    min_area: 1000
    block_size: 9
    param1: 13
    kernel_factor: 5
    rangelow: 0
    rangeup: 255
    targets: 20
    columns: 2
    width: 80
    height: 15

fly:
    min_length: 5
    min_dist_arena: 2
    max_area: 25
    min_area: 10
    min_intensity: 80

tracker:   
    fps: 12
    experimenter: "Sayed"
    crop: 1
    N: 10
    fail: 'failed_arenas/'

arduino:
    board: ArduinoMega

saver:
    video_format: "avi"
    fps: 12

blocks:
    pattern: '.csv'

interface:
    machine_id: "1"
    mode: 'deploy'
