version: 1
formatters:
  simple:
    (): coloredlogs.ColoredFormatter
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  basic:
    (): coloredlogs.ColoredFormatter
    format: '%(asctime)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    level: DEBUG
    stream: ext://sys.stdout
  console_basic:
    class: logging.StreamHandler
    formatter: basic
    level: DEBUG 
    stream: ext://sys.stdout

  file_general:
    class:  logging.handlers.RotatingFileHandler
    level: DEBUG 
    formatter: simple
    filename: general
    maxBytes: 10485760 # 10MB
    backupCount: 3
    encoding: utf8

  file_arduino:
    class:  logging.handlers.RotatingFileHandler
    level: DEBUG 
    formatter: simple
    filename: arduino
    maxBytes: 10485760 # 10MB
    backupCount: 3
    encoding: utf8

  file_tracker:
    class:  logging.handlers.RotatingFileHandler
    level: DEBUG 
    formatter: simple
    filename: tracker
    maxBytes: 10485760 # 10MB
    backupCount: 3
    encoding: utf8



loggers:
  LeMDT.tracker:
    handlers: [console, file_tracker]
    propagate: no
  LeMDT.arduino:
    handlers: [console, file_arduino]
    propagate: no
  LeMDT.cli_gui:
    handlers: [console, file_general]
    propagate: no
  LeMDT.cli_gui:
    handlers: [console, file_general]
    propagate: no
  LeMDT.interface:
    handlers: [console, file_general]
    propagate: no
  LeMDT.saver:
    handlers: [console, file_general]
    propagate: no
  LeMDT.streams:
    handlers: [console, file_general]
    propagate: no
    

