document_experiment_folder <- function() {
  c(
    "@param experiment_folder Path to folder containing IDOC results .csv files"
  )
}

document_gg <- function(x="param") {
    paste0("@", x, " gg ggplot2 object")
}

document_data <- function() {
  c(
    "@param data List with entries roi, controller, border, limits.
    roi and controller must be data.tables generated by loading IDOC data.
    Border is a TODO. Limits is a numeric vector with 2 positions, delineating
    the boundaries of the x axis"
  )
}

document_roi_data <- function() {
  "@param roi_data IDOC tracking dataset where every row captures the position of one animal at one timepoint"
}

document_controller_data <- function() {
  
}

document_analysis <- function() {
  "@param analysis List of processed data including:
  * annotation: every row is a decision zone exit and its appetitive / aversive
  value
  * pi: preference index scored by each animal
  "
}

document_dataset <- function() {
  "@param dataset List of raw data including:
  * roi: every row records the position of one animal at one point in time
  * controller: every row records the status of all IDOC hardware at one point in time
  * limits
  * border
  "
}

document_limits <- function() {
  "@param limits Position of ticks in space axis"
}

document_shape_data <- function() {
  "@param shape_data Data table where every row is a corner of a polygon
   The group field is the same for all corners of the same polygon
   x and y show where on the plot the corner is
  The color and transparency is provided by the other function arguments.
  "
}

document_border <- function() {
  "@param border Number of pixels from center to decision zone edge"
}

document_delay <- function() {
  "@param delay Seconds to shift the representation of the treatments
   on the plot to account for a latency or lag between treatment
  delivery start and arrival to behavioral arena
  "
  
}
